//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaQum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomOrderTemp
    {
        public int ItemNo { get; set; }
        public string customerRef { get; set; }
        public string qty1 { get; set; }
        public string qty10 { get; set; }
    }
}
