//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaQum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Login_Details = new HashSet<Login_Details>();
        }
    
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public string Admin { get; set; }
        public string Engineer { get; set; }
        public Nullable<int> Inventory_Manager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login_Details> Login_Details { get; set; }
    }
}
